name: git-diff-mail
on: pull_request
jobs:
#   run-mail:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: technote-space/get-diff-action@v5
#         with:
#           PATTERNS: |
#             +(src|__tests__)/**/*.ts
#             !src/exclude.ts
#           FILES: |
#             yarn.lock
#             .eslintrc
#       - name: Install Package dependencies
#         run: yarn install
#         if: env.GIT_DIFF
#       - name: Check code style
#         # Check only if there are differences in the source code
#         run: yarn lint
#         if: env.GIT_DIFF
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 8BitJonny/gh-get-current-pr@1.3.0
        id: PR
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16
          sha: ${{ github.event.pull_request.head.sha }}
          # Only return if PR is still open
          filterOutClosed: true
      - uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            +(src|__tests__)/**/*.ts
            !src/exclude.ts
          FORMAT: json
      - run: |
          git diff 'get-diff-action/main...get-diff-action/pull/${{ steps.PR.outputs.number }}/merge' '--diff-filter=AMRC' -- en-us.json -U0 | grep '^[+]' | grep -Ev '^(--- a/|\+\+\+ b/)' > diff-text.txt
      - run: echo '${{ env.GIT_DIFF }}' | jq .
      - name: git diff to artifact
        uses: actions/upload-artifact@v2
        with:
          name: difftext
          path: diff-text.txt
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: difftext
      - name: Checkout
        uses: actions/checkout@v2
#       - name: Get PR
#         uses: ./
#         id: getPR
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#       - name: Display PR properties
#         run: |
#           echo "The PR Number is ${{ steps.getPR.outputs.number }}"
#           echo "The PR Title is ${{ steps.getPR.outputs.pr_title }}"
#           echo "The PR Body is ${{ steps.getPR.outputs.pr_body }}"
#           echo "The PR Url is ${{ steps.getPR.outputs.pr_url }}"
#           echo "The PR Created_At is ${{ steps.getPR.outputs.pr_created_at }}"
#           echo "The PR Merged_At is ${{ steps.getPR.outputs.pr_merged_at }}"
#           echo "The PR Closed_At is ${{ steps.getPR.outputs.pr_closed_at }}"
#       - uses: actions/checkout@v1
#       - uses: 8BitJonny/gh-get-current-pr@master
#         with:
#           github-token: ${{ secrets.GIT_TOKEN }}
#           sha: ${{ github.event.pull_request.head.sha }}
#       - uses: 8BitJonny/gh-get-current-pr@1.3.0
#         id: PR
#         with:
#           github-token: ${{ secrets.GIT_TOKEN }}
#           # Verbose setting SHA when using Pull_Request event trigger to fix #16
#           sha: ${{ github.event.pull_request.head.sha }}
#           # Only return if PR is still open
#           filterOutClosed: true
#       - run: echo "Your PR is ${prNumber} and its JSON is ${prJSON}"
#         if: success() && steps.PR.outputs.number
#         env:
#           prNumber: ${{ steps.PR.outputs.number }}
#           # JSON object with the full PR object
#           prJSON: ${{ steps.PR.outputs.pr }}
#           # Direct access to common PR properties
#           prUrl: ${{ steps.PR.outputs.pr_url }}
#           prTitle: ${{ steps.PR.outputs.pr_title }}
#           prBody: ${{ steps.PR.outputs.pr_body }}
#           prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
#           prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
#           prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: tester101r81@gmail.com
          # Required sender full name (address can be skipped):
          from: Testser # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job completed successfully!
          # Optional HTML body read from file:
          html_body: Please find attachment for the diff changes in translation file
          # Optional carbon copy recipients:
          cc: tester101r81@gmail.com
          # Optional blind carbon copy recipients:
          bcc: tester101r81@gmail.com
          # Optional recipient of the email response:
          reply_to: tester101r81@gmail.com
          # Optional Message ID this message is replying to:
          in_reply_to: <tester101r81@gmail.com>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: difftext, diff-text.txt
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
#       - name: Send some mail
#         uses: wadeww/send-email-action@master
#         with:
#           server_address: smtp.gmail.com
#           port: 465
#           username: ${{secrets.MAIL_USERNAME}}
#           password: ${{secrets.MAIL_PASSWORD}}
#           subject: Workflow finished
#           body: Job completed
#           to: tester101r81@gmail.com
#           from: Me
#   alt-method:
#     runs-on: ubuntu-latest
#     steps: 
#       - name: git fetch
#         run: git fetch
        
#       - name: git diff
#         run: |
#           git diff 'get-diff-action/main...get-diff-action/pull/14/merge' '--diff-filter=AMRC' -- en-us.json -U0 | grep '^[+]' | grep -Ev '^(--- a/|\+\+\+ b/)' > diff-text.txt
#   alt-method:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Configure Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14.x
#       - name: Install dependencies
#         run: yarn install
# #       - name: Publish file changes to Slack
# #         # HERE I run `git diff` in node.js process
# #         run: "SLACK_TOKEN=${{ secrets.GITHUB_TOKEN }} npx ts-node scripts/publishSlackUpdate"
# #       - name: Build TOC
# #         run: make toc
#       - name: Commit build changes
#         uses: EndBug/add-and-commit@v7
#         with:
#           author_name: Docs Builder
#           author_email: tester101r81@gmail.com
#           message: 'Updated build'
#           add: '*.md'
