name: learn-s3

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#       - name: Set AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
#           aws-region: us-east-2
#       - name: Release to S3
#         run: bash scripts/pipeline/release.sh ${{secrets.AWS_BUCKET}} "folder1/myapp.zip" ${{secrets.AWS_KEY_ID}} ${{secrets.AWS_ACCESS_KEY}} "myapp.zip"
      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'en-us.json'

#       - name: Update deployment status (success)
#         if: success()
#         uses: chrnorm/deployment-status@releases/v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           target_url: https://aws-bucket.s3.ap-northeast-2.amazonaws.com/${{steps.S3.outputs.object_key}}/index.html
#           state: 'success'
#           deployment_id: ${{ steps.test.outputs.deployment_id }}
