name: learn-git-diff
on: pull_request
jobs:
  run-mail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            +(src|__tests__)/**/*.ts
            !src/exclude.ts
          FILES: |
            yarn.lock
            .eslintrc
      - name: Install Package dependencies
        run: yarn install
        if: env.GIT_DIFF
      - name: Check code style
        # Check only if there are differences in the source code
        run: yarn lint
        if: env.GIT_DIFF
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            +(src|__tests__)/**/*.ts
            !src/exclude.ts
          FORMAT: json
      - run: |
          git diff 'get-diff-action/main...get-diff-action/pull/14/merge' '--diff-filter=AMRC' -- en-us.json
      - run: echo '${{ env.GIT_DIFF }}' | jq .
#       - name: git diff to artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: difftext
#           path: diff-text.txt
#   alt-method:
#     runs-on: ubuntu-latest
#     steps: 
#       - name: git fetch
#         run: git fetch
        
#       - name: git diff
#         run: |
#           git diff 'get-diff-action/main...get-diff-action/pull/14/merge' '--diff-filter=AMRC' -- en-us.json -U0 | grep '^[+]' | grep -Ev '^(--- a/|\+\+\+ b/)' > diff-text.txt
#   alt-method:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Configure Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14.x
#       - name: Install dependencies
#         run: yarn install
# #       - name: Publish file changes to Slack
# #         # HERE I run `git diff` in node.js process
# #         run: "SLACK_TOKEN=${{ secrets.GITHUB_TOKEN }} npx ts-node scripts/publishSlackUpdate"
# #       - name: Build TOC
# #         run: make toc
#       - name: Commit build changes
#         uses: EndBug/add-and-commit@v7
#         with:
#           author_name: Docs Builder
#           author_email: tester101r81@gmail.com
#           message: 'Updated build'
#           add: '*.md'
